title: "Mutasem A. Razzek"
name: "Mutasem A. Razzek"
email: "mabdalrazzek@gmail.com"
description: "Mechanical & Aerospace Engineer | EIT | Private Pilot"
url: "https://mutasemrazz.github.io"
baseurl: "/portfolio" # repository name

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-include-cache

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Default settings
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true

# Optional: Google Analytics or Disqus can go here
# google_analytics: UA-XXXXXXXXX-X
# disqus:
#   shortname: your-disqus-shortname
